/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.visao;
import br.com.controle.Conexao;
import java.sql.*;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author lucas
 */
public class TelaEstoque extends javax.swing.JFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
    ArrayList<String> dados = new ArrayList<>();

    /**
     * Creates new form TelaEstoque
     */
    public TelaEstoque() {
        initComponents();
        
        conexao = Conexao.conector();
        carregaTabela();
        if(conexao != null){
            jLabel4.setText("Conexão estabelecida!");
        }else{
            jLabel4.setText("Conexão não estabelecida!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTcod = new javax.swing.JTextField();
        jTnome = new javax.swing.JTextField();
        jTest = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jBdel = new javax.swing.JButton();
        jBcad = new javax.swing.JButton();
        jBedit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTtipo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAB = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 153));
        setForeground(java.awt.Color.white);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Código:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        jTcod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcodActionPerformed(evt);
            }
        });
        getContentPane().add(jTcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 330, -1));

        jTnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 330, -1));

        jTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTestActionPerformed(evt);
            }
        });
        getContentPane().add(jTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 330, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\lucas\\Downloads\\signal.png")); // NOI18N
        jLabel4.setText("PlaceHolder");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 110));

        jBdel.setText("Remover produto");
        jBdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdelActionPerformed(evt);
            }
        });
        getContentPane().add(jBdel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));

        jBcad.setText("Cadastrar produto");
        jBcad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadActionPerformed(evt);
            }
        });
        getContentPane().add(jBcad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        jBedit.setText("Editar produto");
        jBedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeditActionPerformed(evt);
            }
        });
        getContentPane().add(jBedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Estoque:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        jTtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTtipoActionPerformed(evt);
            }
        });
        getContentPane().add(jTtipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 330, -1));

        jTAB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Tipo", "Estoque"
            }
        ));
        jScrollPane1.setViewportView(jTAB);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 430, 420));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\lucas\\Downloads\\95b743fbe5bf5dc605b1ee8c7768ab4f.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTcodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcodActionPerformed

    private void jTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTestActionPerformed

    private void jTnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnomeActionPerformed

    private void jTtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTtipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTtipoActionPerformed

    private void jBcadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadActionPerformed
        // TODO add your handling code here:
        salvar();
    }//GEN-LAST:event_jBcadActionPerformed

    private void jBeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeditActionPerformed
        // TODO add your handling code here:
        atualizar();
    }//GEN-LAST:event_jBeditActionPerformed

    private void jBdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdelActionPerformed
        // TODO add your handling code here:
        excluir();
    }//GEN-LAST:event_jBdelActionPerformed
    private void carregaTabela(){
        DefaultTableModel dados = (DefaultTableModel) jTAB.getModel();
        dados.setNumRows(0);
        jTAB.getColumnModel().getColumn(0).setPreferredWidth(20);
        jTAB.getColumnModel().getColumn(1).setPreferredWidth(80);
        jTAB.getColumnModel().getColumn(2).setPreferredWidth(80);
        jTAB.getColumnModel().getColumn(3).setPreferredWidth(30);
        
        try{  
            pst = conexao.prepareStatement("select * from estoque;");
            rs = pst.executeQuery();
            
            while(rs.next()){
                dados.addRow(new Object[]{
                rs.getInt(1),
                rs.getString(2),
                rs.getString(3),
                rs.getInt(4)
                });
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcad;
    private javax.swing.JButton jBdel;
    private javax.swing.JButton jBedit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTAB;
    private javax.swing.JTextField jTcod;
    private javax.swing.JTextField jTest;
    private javax.swing.JTextField jTnome;
    private javax.swing.JTextField jTtipo;
    // End of variables declaration//GEN-END:variables
    private void salvar() {
        String sql = "insert into estoque (cod, nome, tipo, quant) values(?,?,?,?)";
        try{
           pst = conexao.prepareStatement(sql);
           pst.setInt(1, Integer.parseInt(jTcod.getText()));
           pst.setString(2, jTnome.getText());
           pst.setString(3, jTtipo.getText());
           pst.setInt(4, Integer.parseInt(jTest.getText()));
           System.out.println(pst);
           
           int resultado = pst.executeUpdate();
           if(resultado == 1){
              JOptionPane.showMessageDialog(null, "Produto cadastrado com sucesso!");
              jTcod.setText("");
              jTnome.setText("");
              jTtipo.setText(""); //pode ser null ao invés de ""
              jTest.setText("");
           }else{
               JOptionPane.showMessageDialog(null, "Impossível cadastrar este produto!");
           }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        carregaTabela();
    }

    private void excluir() {
        String sql = "DELETE FROM estoque where cod = ?";
        try{
            pst = conexao.prepareStatement(sql);
            pst.setString(1, jTcod.getText());
            System.out.println(pst);
            
            int resultado = pst.executeUpdate();
            if(resultado == 1){
                JOptionPane.showMessageDialog(null, "Produto deletado com sucesso!");
                jTcod.setText("");
                jTnome.setText("");
                jTtipo.setText("");
                jTest.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Impossível deletar este produto!.");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        carregaTabela();
    }



    private void atualizar() {
        String sql = "update estoque set nome=?, tipo=?, quant=? where cod=?";
        try{
            pst = conexao.prepareStatement(sql);
            pst.setInt(4, Integer.parseInt(jTcod.getText()));
            pst.setString(1, jTnome.getText());
            pst.setString(2, jTtipo.getText());
            pst.setInt(3,Integer.parseInt(jTest.getText()));
           
            System.out.println(pst);
           
            int atualizado = pst.executeUpdate();
            if(atualizado == 1){
                JOptionPane.showMessageDialog(null, "Produto atualizado com sucesso!");
                
                jTnome.setText(null);//apaga o campo preenchido
                jTtipo.setText(null);
                jTest.setText(null);
            }else{
                JOptionPane.showMessageDialog(null, "Impossível atualizar este produto!");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        carregaTabela();
    }
    
}
